# Generated by Django 5.2.7 on 2026-06-17
#
# Scoped to a single change: add Cover.display_submitter_name. Django's
# makemigrations also offered two unrelated choices-only AlterField ops
# (covermarking.review_status, submissiontransaction.action) that reflect
# pre-existing model/migration drift; those are intentionally NOT included
# here so this feature migration stays focused. (Choices changes emit no SQL.)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contribution_timestamped'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='display_submitter_name',
            field=models.BooleanField(default=False, help_text='Whether the submitter opted in to show their name on the public cover detail page'),
        ),
    ]
