# Generated by Django 5.2.7 on 2026-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_cover_display_submitter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covermarking',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs revision')], default='approved', help_text='Editor moderation state for this cover-marking association.', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissiontransaction',
            name='action',
            field=models.CharField(choices=[('submit', 'Record submitted'), ('edit_submission', 'Edited submission'), ('editor_edit', 'Editor edit'), ('approve', 'Approved'), ('reject', 'Rejected'), ('catalog_direct_edit', 'Catalog direct edit'), ('restore_version', 'Restored version'), ('record_create', 'Record created'), ('record_update', 'Record updated'), ('record_delete', 'Record deleted'), ('draft_deleted', 'Draft deleted'), ('marking_removed', 'Marking removed'), ('marking_restored', 'Marking restored'), ('cover_removed', 'Cover removed'), ('cover_restored', 'Cover restored')], max_length=40),
        ),
    ]
