# Generated by Django 5.2.7 on 2026-06-18 (Issue #22).
#
# Scoped to ONLY the Marking.is_reviewed AddField. `makemigrations` also wants
# to emit AlterFields for CoverMarking.review_status and
# SubmissionTransaction.action -- those are staging's pre-existing committed
# model drift owned by PR #58 (the prod-deploy fix), NOT this issue. They are
# deliberately excluded here so #22 stays isolated; PR #58 commits them.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_cover_display_submitter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marking',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='A state editor has personally vetted this record (Issue #22).'),
        ),
    ]
