# Generated by Django 5.2.7 on 2026-06-18 (Issue #22).
#
# This was renumbered after PR #58 merged its own 0004 migration.
# Keep this AddField after 0004_alter_covermarking_review_status_and_more so
# Django has one common migration leaf on staging.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_covermarking_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marking',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='A state editor has personally vetted this record (Issue #22).'),
        ),
    ]
