# Generated by Django 5.2.7 on 2026-06-18 (Issue #22).
#
# This was renumbered after PR #58 merged its own 0004 migration.
# The first staging deploy partly applied the original AddField, then failed
# before Django recorded this migration. Keep the database step idempotent so a
# retry records migration state when the is_reviewed column already exists.

from django.db import migrations, models


def add_is_reviewed_if_missing(apps, schema_editor):
    Marking = apps.get_model('common', 'Marking')
    table_name = Marking._meta.db_table
    column_name = 'is_reviewed'

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if column_name in existing_columns:
        return

    field = models.BooleanField(default=False, help_text='A state editor has personally vetted this record (Issue #22).')
    field.set_attributes_from_name(column_name)
    schema_editor.add_field(Marking, field)


def remove_is_reviewed_if_present(apps, schema_editor):
    Marking = apps.get_model('common', 'Marking')
    table_name = Marking._meta.db_table
    column_name = 'is_reviewed'

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if column_name not in existing_columns:
        return

    field = models.BooleanField(default=False, help_text='A state editor has personally vetted this record (Issue #22).')
    field.set_attributes_from_name(column_name)
    schema_editor.remove_field(Marking, field)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_covermarking_review_status_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_is_reviewed_if_missing, remove_is_reviewed_if_present),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='marking',
                    name='is_reviewed',
                    field=models.BooleanField(default=False, help_text='A state editor has personally vetted this record (Issue #22).'),
                ),
            ],
        ),
    ]
