# Generated by Django 5.2.7 on 2026-06-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_marking_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Free-text description / notes about the cover, shown on the public cover detail page'),
        ),
    ]
