# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_cover_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Editor-assigned reference identifier",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="postoffice",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Editor-assigned reference identifier",
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="dateseen",
            constraint=models.UniqueConstraint(
                fields=("subject_type", "subject_id", "date", "granularity"),
                name="dates_seen_subject_date_granularity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(
                fields=("storage_filename", "subject_type", "subject_id"),
                name="image_storage_subject_unique",
            ),
        ),
    ]
