# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_region_postoffice_codes_dedupe_constraints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="covervaluation",
            constraint=models.UniqueConstraint(
                fields=("cover", "appraisal_date"),
                name="cover_valuation_cover_appraisal_date_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="citation",
            constraint=models.UniqueConstraint(
                fields=("reference_work", "subject_type", "subject_id", "citation_detail"),
                name="citation_reference_subject_detail_unique",
            ),
        ),
    ]
