# Generated by Django 5.2.7 on 2026-06-28 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_ascc_additive_import_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marking',
            name='marking_manuscript_consistency',
        ),
        migrations.AlterField(
            model_name='marking',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='markings', to='common.color'),
        ),
        migrations.AddConstraint(
            model_name='marking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_irreg__isnull', True), ('is_manuscript', True), ('lettering__isnull', True), ('shape__isnull', True)), models.Q(('is_irreg__isnull', False), ('is_manuscript', False)), _connector='OR'), name='marking_manuscript_consistency'),
        ),
    ]
