# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_remove_marking_marking_manuscript_consistency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissiontransaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("submit", "Record submitted"),
                    ("edit_submission", "Edited submission"),
                    ("editor_edit", "Editor edit"),
                    ("approve", "Approved"),
                    ("reject", "Rejected"),
                    ("catalog_direct_edit", "Catalog direct edit"),
                    ("restore_version", "Restored version"),
                    ("record_create", "Record created"),
                    ("record_update", "Record updated"),
                    ("record_delete", "Record deleted"),
                    ("draft_deleted", "Draft deleted"),
                    ("contribution_superseded", "Contribution superseded"),
                    ("marking_removed", "Marking removed"),
                    ("marking_restored", "Marking restored"),
                    ("cover_removed", "Cover removed"),
                    ("cover_restored", "Cover restored"),
                ],
                max_length=40,
            ),
        ),
    ]
