# Generated by Codex on 2026-08-03

from datetime import date

from django.db import migrations, models


def key_for_parts(year, month, day):
    parts = []
    if year is not None:
        parts.append("Y{:04d}".format(year))
    if month is not None:
        parts.append("M{:02d}".format(month))
    if day is not None:
        parts.append("D{:02d}".format(day))
    return "-".join(parts)


def backfill_date_components(apps, schema_editor):
    DateSeen = apps.get_model("common", "DateSeen")
    for row in DateSeen.objects.all().iterator():
        if row.date is None:
            continue
        granularity = (row.granularity or "DAY").upper()
        row.date_year = row.date.year
        if granularity == "YEAR":
            row.date_month = None
            row.date_day = None
            row.date = date(row.date.year, 1, 1)
        elif granularity == "MONTH":
            row.date_month = row.date.month
            row.date_day = None
            row.date = date(row.date.year, row.date.month, 1)
        else:
            row.date_month = row.date.month
            row.date_day = row.date.day
            row.granularity = "DAY"
        row.date_key = key_for_parts(row.date_year, row.date_month, row.date_day)
        row.save(
            update_fields=[
                "date",
                "granularity",
                "date_year",
                "date_month",
                "date_day",
                "date_key",
            ]
        )


def clear_date_components(apps, schema_editor):
    DateSeen = apps.get_model("common", "DateSeen")
    DateSeen.objects.update(date_year=None, date_month=None, date_day=None, date_key="")


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_contribution_superseded_action"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dateseen",
            name="dates_seen_subject_date_granularity_unique",
        ),
        migrations.AddField(
            model_name="dateseen",
            name="date_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dateseen",
            name="date_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dateseen",
            name="date_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dateseen",
            name="date_key",
            field=models.CharField(default="", editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dateseen",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Sortable calendar date when known date parts form one",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dateseen",
            name="granularity",
            field=models.CharField(
                choices=[
                    ("DAY", "Day"),
                    ("MONTH", "Month"),
                    ("YEAR", "Year"),
                    ("MONTH_ONLY", "Month only"),
                    ("DAY_ONLY", "Day only"),
                    ("YEAR_DAY", "Year and day"),
                    ("MONTH_DAY", "Month and day"),
                ],
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_date_components, clear_date_components),
        migrations.AddConstraint(
            model_name="dateseen",
            constraint=models.UniqueConstraint(
                fields=("subject_type", "subject_id", "granularity", "date_key"),
                name="dates_seen_subject_parts_unique",
            ),
        ),
    ]
