# Generated by Django 5.2.7 on 2026-08-05 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_contribution_superseded_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marking',
            name='earliest_seen',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='marking',
            name='earliest_seen_granularity',
            field=models.CharField(blank=True, choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], editable=False, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='marking',
            name='latest_seen',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='marking',
            name='latest_seen_granularity',
            field=models.CharField(blank=True, choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], editable=False, max_length=5, null=True),
        ),
        migrations.AddIndex(
            model_name='marking',
            index=models.Index(fields=['earliest_seen'], name='marking_earliest_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='marking',
            index=models.Index(fields=['latest_seen'], name='marking_latest_seen_idx'),
        ),
    ]
