# Generated by Claude Code on 2026-08-05 (issue #59 fix)
#
# Backfills Marking.earliest_seen / latest_seen (+granularities) from
# dates_seen + cover_markings. Runs automatically during deploy
# (deploy/deploy.sh -> `manage.py migrate --noinput`). Chunked so a
# million-row volume-test database backfills in minutes and staging's
# few thousand rows in seconds; each chunk is 2 SELECTs + batched UPDATEs.
from django.db import migrations

CHUNK = 5000


def backfill_date_ranges(apps, schema_editor):
    # Pure helper shared with the runtime signal path and the recompute
    # management command; it accepts model classes, so historical models
    # (which lack custom managers/methods) work identically.
    from common.date_range import refresh_marking_date_ranges

    Marking = apps.get_model("common", "Marking")
    DateSeen = apps.get_model("common", "DateSeen")
    CoverMarking = apps.get_model("common", "CoverMarking")

    ids = list(Marking.objects.order_by("pk").values_list("pk", flat=True))
    for start in range(0, len(ids), CHUNK):
        refresh_marking_date_ranges(
            ids[start:start + CHUNK],
            Marking=Marking,
            DateSeen=DateSeen,
            CoverMarking=CoverMarking,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_marking_earliest_seen_and_more"),
    ]

    operations = [
        # Reverse is a no-op: 0011's reversal drops the columns anyway.
        migrations.RunPython(backfill_date_ranges, migrations.RunPython.noop),
    ]
