# Generated by Codex on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_dateseen_partial_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="marking",
            name="display_submitter_name",
            field=models.BooleanField(
                default=False,
                help_text="Whether the submitter opted in to show their name on the public marking detail page",
            ),
        ),
    ]
