# Generated by Codex on 2026-08-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_backfill_marking_date_ranges"),
        ("common", "0012_marking_display_submitter_name"),
    ]

    operations = []
