# Generated by Django 5.2.7 on 2026-08-05 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_merge_staging_dateselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cropped_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='common.image'),
        ),
    ]
