# Generated by Django 5.2.7 on 2026-08-11 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_image_cropped_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontransaction',
            name='action',
            field=models.CharField(choices=[('submit', 'Record submitted'), ('edit_submission', 'Edited submission'), ('editor_edit', 'Editor edit'), ('approve', 'Approved'), ('reject', 'Rejected'), ('catalog_direct_edit', 'Catalog direct edit'), ('restore_version', 'Restored version'), ('record_create', 'Record created'), ('record_update', 'Record updated'), ('record_delete', 'Record deleted'), ('draft_deleted', 'Draft deleted'), ('contribution_superseded', 'Contribution superseded'), ('marking_removed', 'Marking removed'), ('marking_restored', 'Marking restored'), ('cover_removed', 'Cover removed'), ('cover_restored', 'Cover restored'), ('contribution_archived', 'Contribution archived'), ('contribution_restored', 'Contribution restored')], max_length=40),
        ),
        migrations.CreateModel(
            name='ContributionRecycleBin',
            fields=[
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recycle_bin_entry', serialize=False, to='common.contribution')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions_archived', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Contribution',
                'verbose_name_plural': 'Archived Contributions',
                'db_table': 'contribution_recycle_bin',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['archived_at'], name='contributio_archive_4bf550_idx')],
            },
        ),
    ]
