# Generated by Django 5.2.7 on 2026-08-12 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_contribution_recycle_bin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postofficeregion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='postoffice',
            name='population',
            field=models.PositiveIntegerField(blank=True, help_text='Contemporary population as recorded by the source catalog, where given', null=True),
        ),
        migrations.AddField(
            model_name='postofficeregion',
            name='valid_from',
            field=models.DateField(blank=True, help_text="First date this jurisdiction applied; null = from the region's own start", null=True),
        ),
        migrations.AddField(
            model_name='postofficeregion',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Last date this jurisdiction applied; null = still current', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='postofficeregion',
            unique_together={('post_office', 'region', 'valid_from')},
        ),
        migrations.CreateModel(
            name='Postmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name as printed in the source, e.g. Gerrard T. Conn', max_length=255)),
                ('sort_name', models.CharField(db_index=True, help_text='Surname-first form used for ordering and de-duplication', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postmaster',
                'verbose_name_plural': 'Postmasters',
                'db_table': 'postmaster',
                'ordering': ['sort_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PostmasterTenure',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('tenure_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('appointment', 'Appointment'), ('discontinued', 'Office discontinued'), ('reappointment', 'Reappointment'), ('unknown', 'Unknown')], default='appointment', max_length=16)),
                ('date_appointed', models.DateField(blank=True, help_text='Null when the source gives no usable date', null=True)),
                ('date_appointed_granularity', models.CharField(blank=True, choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], help_text='How much of date_appointed the source actually stated', max_length=5, null=True)),
                ('source_ref', models.CharField(blank=True, default='', help_text='Cell reference in the source workbook, e.g. T3:r15904', max_length=32)),
                ('rules_version', models.PositiveSmallIntegerField(blank=True, help_text='RULES.md version that decoded this row', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postmaster_tenures', to='common.postoffice')),
                ('postmaster', models.ForeignKey(blank=True, help_text='Null for an office-level event such as a discontinuation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenures', to='common.postmaster')),
            ],
            options={
                'verbose_name': 'Postmaster Tenure',
                'verbose_name_plural': 'Postmaster Tenures',
                'db_table': 'postmaster_tenure',
                'ordering': ['post_office__name', 'date_appointed', 'tenure_id'],
            },
        ),
        migrations.AddIndex(
            model_name='postmaster',
            index=models.Index(fields=['name'], name='postmaster_name_idx'),
        ),
        migrations.AddIndex(
            model_name='postmastertenure',
            index=models.Index(fields=['post_office', 'date_appointed'], name='tenure_office_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='postmastertenure',
            constraint=models.CheckConstraint(condition=models.Q(('event__in', ['appointment', 'discontinued', 'reappointment', 'unknown'])), name='tenure_event_valid'),
        ),
        migrations.AddConstraint(
            model_name='postmastertenure',
            constraint=models.UniqueConstraint(fields=('post_office', 'postmaster', 'date_appointed', 'event'), name='tenure_office_person_date_event_unique'),
        ),
    ]
