# Generated by Claude Code on 2026-08-24 (issue #121 fix)
#
# Re-runs the Marking.earliest_seen / latest_seen backfill so existing
# databases pick up the issue-#121 boundary rule (a precise date inside a
# coarse row's span now supplies that boundary; see common.date_range._resolve).
#
# Why a second backfill instead of editing 0012: that migration imports
# refresh_marking_date_ranges at runtime, so a FRESH install already backfills
# with the new rule while an ALREADY-MIGRATED box still holds the old values.
# Rather than freeze a stale copy of the helper inside 0012, both paths are made
# to converge here -- on a fresh install this is a no-op, on an existing one it
# is the correction. The columns are a pure idempotent cache over dates_seen +
# cover_markings, so re-running is always safe.
#
# Runs automatically during deploy (deploy/deploy.sh -> `manage.py migrate
# --noinput`), so woco.dev repairs itself with no manual step. Chunked like
# 0012: each chunk is 2 SELECTs + batched UPDATEs, via bulk_update only (no
# save(), no signals, no django-reversion churn).
from django.db import migrations

CHUNK = 5000


def recompute_date_ranges(apps, schema_editor):
    from common.date_range import refresh_marking_date_ranges

    Marking = apps.get_model("common", "Marking")
    DateSeen = apps.get_model("common", "DateSeen")
    CoverMarking = apps.get_model("common", "CoverMarking")

    ids = list(Marking.objects.order_by("pk").values_list("pk", flat=True))
    for start in range(0, len(ids), CHUNK):
        refresh_marking_date_ranges(
            ids[start:start + CHUNK],
            Marking=Marking,
            DateSeen=DateSeen,
            CoverMarking=CoverMarking,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_postmaster_and_county_support"),
    ]

    operations = [
        # Reverse is a no-op: the columns are derived, so reverting the code and
        # re-running the recompute command reproduces the old values exactly.
        migrations.RunPython(recompute_date_ranges, migrations.RunPython.noop),
    ]
